// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMOxchECoAtKdxQ5jv42Vwd3rYQli0xWU',
    appId: '1:304064985313:web:2b334173da10ece35bdfa0',
    messagingSenderId: '304064985313',
    projectId: 'budget-bee-app-9fda6',
    authDomain: 'budget-bee-app-9fda6.firebaseapp.com',
    storageBucket: 'budget-bee-app-9fda6.firebasestorage.app',
    measurementId: 'G-XWNES9JNK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbHND-CwpQRVJFtp0UrLSaWq23eEsHjgk',
    appId: '1:304064985313:android:fd1cd2be73076ed95bdfa0',
    messagingSenderId: '304064985313',
    projectId: 'budget-bee-app-9fda6',
    storageBucket: 'budget-bee-app-9fda6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GDxQ3-Nc_WSAhE8muC_V3WNurmQqLDA',
    appId: '1:304064985313:ios:545934ce340fdad85bdfa0',
    messagingSenderId: '304064985313',
    projectId: 'budget-bee-app-9fda6',
    storageBucket: 'budget-bee-app-9fda6.firebasestorage.app',
    iosBundleId: 'com.example.budgetBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GDxQ3-Nc_WSAhE8muC_V3WNurmQqLDA',
    appId: '1:304064985313:ios:545934ce340fdad85bdfa0',
    messagingSenderId: '304064985313',
    projectId: 'budget-bee-app-9fda6',
    storageBucket: 'budget-bee-app-9fda6.firebasestorage.app',
    iosBundleId: 'com.example.budgetBee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMOxchECoAtKdxQ5jv42Vwd3rYQli0xWU',
    appId: '1:304064985313:web:7132db255335b37a5bdfa0',
    messagingSenderId: '304064985313',
    projectId: 'budget-bee-app-9fda6',
    authDomain: 'budget-bee-app-9fda6.firebaseapp.com',
    storageBucket: 'budget-bee-app-9fda6.firebasestorage.app',
    measurementId: 'G-N7NJE4QSJL',
  );
}
